config/routes.rb
Rails.application.routes.draw do
  resources :categories
  resources :authors
  devise_for :users
  get 'inicial/index'
  root 'inicial#index'
  resources :books
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
	has_many :books
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	belongs_to :category, :optional => true
	belongs_to :author, :optional => true

	def self.search(search)
  		where("titulo LIKE ?", "%#{search}%") 
	end

	has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :books
end

app/models/user.rb
class User < ApplicationRecord
	has_many :books

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: [:show, :edit, :update, :destroy]

  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.all
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: 'Author was successfully created.' }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1
  # PATCH/PUT /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to @author, notice: 'Author was successfully updated.' }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author.destroy
    respond_to do |format|
      format.html { redirect_to authors_url, notice: 'Author was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def author_params
      params.require(:author).permit(:name)
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:edit, :show, :update, :destroy]
  before_action:authenticate_user!, except: [:index]

  # GET /books
  # GET /books.json
  def index
    @books = Book.all
  end

  def index
    @books = Book.all
    if params[:search]
      @books = Book.search(params[:search]).order("created_at DESC")
    else
      @books = Book.all.order("created_at DESC")
    end
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = current_user.books.build
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = current_user.books.build(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Livro anunciado com sucesso.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Informações atualizadas com sucesso.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Livro foi apagado.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:titulo, :descricao, :opcao, :preco, :image, :autor, :categoria)
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/inicial_controller.rb
class InicialController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
  	@user = User.find(params[:id])
  	@user_books = @user.books
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/inicial_helper.rb
module InicialHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/authors/_form.html.erb
<%= form_with(model: author, local: true) do |form| %>
  <% if author.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
      <% author.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/authors/edit.html.erb
<h1>Editing Author</h1>

<%= render 'form', author: @author %>

<%= link_to 'Show', @author %> |
<%= link_to 'Back', authors_path %>

app/views/authors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Authors</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @authors.each do |author| %>
      <tr>
        <td><%= author.name %></td>
        <td><%= link_to 'Show', author %></td>
        <td><%= link_to 'Edit', edit_author_path(author) %></td>
        <td><%= link_to 'Destroy', author, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Author', new_author_path %>

app/views/authors/new.html.erb
<h1>New Author</h1>

<%= render 'form', author: @author %>

<%= link_to 'Back', authors_path %>

app/views/authors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @author.name %>
</p>

<%= link_to 'Edit', edit_author_path(@author) %> |
<%= link_to 'Back', authors_path %>

app/views/books/_form.html.erb
<%= form_with model: book, local: true, url: books_path, html: { multipart: true } do |form| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :titulo %>
    <br>
    <%= form.text_field :titulo %>
  </div>

  <div class="field">
    <%= form.label :descricao %>
    <br>
    <%= form.text_area :descricao %>
  </div>

  <div class="field">
    <%= form.label :opcao %>
    <%= form.select :opcao, [['Vender'],['Doação']], :prompt => "Selecione" %>
    <%= form.label :preco %> <%= form.text_field :preco %>
  </div>

  <div class="field">
    <%= form.label :categoria %>
    <br>
    <%= form.text_field :categoria %>
  </div>

  <div class="field">
    <%= form.label :autor %>
    <br>
    <%= form.text_field :autor %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>

<% end %>

app/views/books/edit.html.erb
<h1>Editando livro</h1>

<%= render 'form', book: @book %>

<%= link_to 'Visualizar', @book %> |
<a href="/books">Voltar</a>

app/views/books/index.html.erb
<!DOCTYPE html>

<html lang="pt-br">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="css/bootstrap.min.css">
    <link rel="stylesheet" href="css/style.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/css?family=Abel|Montserrat|Patua+One" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script> 

  </head>

  <body>
    <section class="fundo">
    <nav class="navbar navbar-inverse">
      <div class="container-fluid">
        <div class="navbar-header">
          <div class="navbar-brand" style="color: #fff"><div style="font-family: 'Patua One', cursive">Venda/Doação de Livros</div></div>
        </div>
        <ul class="nav navbar-nav">
          <li><a href="/" style="color: #fff">Home</a></li>
          <li><a href="/books" style="color: #fff">Livros</a></li>
          <li><a href="#" style="color: #fff">Sobre</a></li>
          <li><a href="#" style="color: #fff">Contato</a></li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
        <% if user_signed_in? %>
          <button class="btn btn-primary navbar-btn"><%= link_to "Perfil", user_path(current_user) %></button>
          <button class="btn btn-danger navbar-btn"><%= link_to "Sair", destroy_user_session_path, method: :delete %></button>
        <% else %>
          <button class="btn btn-success navbar-btn"><%= link_to "Entrar", user_session_path %></button>
        <% end %>
      </form>
      </div>
    </nav>

    <div class="container-fluid">
  <div class="row content">
    <div class="col-sm-3 sidenav">
      <br>
      <br>
      <br>
      <br>
      <%= form_tag(books_path, :method => "get", id: "search-form") do %>
        <%= text_field_tag :search, params[:search], placeholder: "Search..." %>
        <%= submit_tag "Search", :name => nil %>
      <% end %>
      <br>
      <ul class="nav nav-pills nav-stacked">
        <li class="active"><a href="books/new">Anunciar Livro</a></li>
      </ul><br>
    </div>


    <div class="col-sm-9">
        <h1 class="font-tit">Livros</h1>
        <hr size="30">
      <div class="row">
        <% @books.each do |book| %>
          <div class="col-sm-4 col-md-3">
            <div class="thumbnail" style='color: #000'>
              <%= link_to image_tag(book.image.url(:thumb)), book %>
              <div class="caption text-center">
                <h3 class="font-tumb"><%= book.titulo %></h3>
                <h4 class="font-tumb"><%= book.opcao %><%= book.preco %></h4>                
              </div>
            </div>
          </div>
        <% end %>
        </div>

    </div>
  </section>
  </body>

</html>

app/views/books/new.html.erb
<!DOCTYPE html>

<html lang="pt-br">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="css/bootstrap.min.css">
    <link rel="stylesheet" href="css/style.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/css?family=Abel|Montserrat|Patua+One" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script> 

  </head>

  <body>
    
    <nav class="navbar navbar-inverse">
      <div class="container-fluid">
        <div class="navbar-header">
          <div class="navbar-brand" style="color: #fff"><div style="font-family: 'Patua One', cursive">Venda/Doação de Livros</div></div>
        </div>
        <ul class="nav navbar-nav">
          <li><a href="/" style="color: #fff">Home</a></li>
          <li><a href="/books" style="color: #fff">Livros</a></li>
          <li><a href="#" style="color: #fff">Sobre</a></li>
          <li><a href="#" style="color: #fff">Contato</a></li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
        <% if user_signed_in? %>
          <button class="btn btn-primary navbar-btn"><%= link_to "Perfil", user_path(current_user) %></button>
          <button class="btn btn-danger navbar-btn"><%= link_to "Sair", destroy_user_session_path, method: :delete %></button>
        <% else %>
          <button class="btn btn-success navbar-btn"><%= link_to "Entrar", user_session_path %></button>
        <% end %>
      </form>
      </div>
    </nav>

    <div class="container-fluid">
  		<h1>Anunciar livro</h1>
  		<hr>
  		<div class="col-sm-9">
			<%= render 'form', book: @book %>
			<%= link_to 'Voltar', books_path %>
		</div>
    </div>

  </body>

</html>

app/views/books/show.html.erb
<!DOCTYPE html>

<html lang="pt-br">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="css/bootstrap.min.css">
    <link rel="stylesheet" href="css/style.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/css?family=Abel|Montserrat|Patua+One" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script> 

  </head>

  <body>
  	
    <nav class="navbar navbar-inverse">
      <div class="container-fluid">
        <div class="navbar-header">
          <div class="navbar-brand" style="color: #fff"><div style="font-family: 'Patua One', cursive">Venda/Doação de Livros</div></div>
        </div>
        <ul class="nav navbar-nav">
          <li><a href="/" style="color: #fff">Home</a></li>
          <li><a href="/books" style="color: #fff">Livros</a></li>
          <li><a href="#" style="color: #fff">Sobre</a></li>
          <li><a href="#" style="color: #fff">Contato</a></li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
        <% if user_signed_in? %>
          <button class="btn btn-primary navbar-btn"><%= link_to "Perfil", user_path(current_user) %></button>
          <button class="btn btn-danger navbar-btn"><%= link_to "Sair", destroy_user_session_path, method: :delete %></button>
        <% else %>
          <button class="btn btn-success navbar-btn"><%= link_to "Entrar", user_session_path %></button>
        <% end %>
      </form>
      </div>
    </nav>
    <div class="container">
      <div class="col-md-9">
        <h2><%= @book.titulo %></h2>
        <hr> 
      </div>
      <div class="row">
      <div class="col-md-4">
        <%= image_tag @book.image.url(:medium) %>
      </div>
      <div class="col-md-4"> 
        <h2>Contato:</h2>
        <p>
          <strong>Email do anunciante:</strong>
          teste@teste.com
        </p>
        <hr>
        <h2>Detalhes do livro:</h2>
        <p>
          <strong>Autor:</strong>
          <%= @book.autor %>
        </p> 
        <p>
          <strong>Categoria:</strong>
          <%= @book.categoria %>
        </p> 
        <p>
          <strong>Descrição:</strong>
          <%= @book.descricao %>
        </p>
        <p>
          <strong>Opção:</strong>
          <%= @book.opcao %>
        </p>
        
        <button type="submit" class="btn btn-primary"><%= link_to 'Edit', edit_book_path(@book) %></a>
        <button type="submit" class="btn btn-danger"><%= link_to 'Excluir', @book, method: :delete, data: { confirm: 'Você tem certeza?' } %></a>
      </div>
      </div>
    </div>
  </body>

</html>

app/views/categories/_form.html.erb
<%= form_with(model: category, local: true) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/inicial/index.html.erb
<!DOCTYPE html>

<html lang="pt-br">

	<head>
		
		<meta charset="utf-8">
    	<meta name="viewport" content="width=device-width, initial-scale=1">
    	<link rel="stylesheet" href="css/bootstrap.min.css">
    	<link rel="stylesheet" href="css/style.css">
    	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    	<link href="https://fonts.googleapis.com/css?family=Abel|Montserrat|Patua+One" rel="stylesheet">
    	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script> 

	</head>

	<body>


		<div class="bw-gradient"></div>
		<section class="header-site">
			<nav class="navbar navbar-inverse">
      			<div class="container-fluid">
        			<div class="navbar-header">
        				<div class="navbar-brand" style="color: #fff"><div style="font-family: 'Patua One', cursive">Venda/Doação de Livros</div></div>
        			</div>
        			<ul class="nav navbar-nav">
        				<li><a href="/" style="color: #fff">Home</a></li>
        				<li><a href="/books" style="color: #fff">Livros</a></li>
        				<li><a href="#" style="color: #fff">Sobre</a></li>
        				<li><a href="#" style="color: #fff">Contato</a></li>
        			</ul>
                    <form class="form-inline my-2 my-lg-0">
        			     <% if user_signed_in? %>
        			 	    <button class="btn btn-primary navbar-btn"><%= link_to "Perfil", user_path(current_user) %></button>
        				    <button class="btn btn-danger navbar-btn"><%= link_to "Sair", destroy_user_session_path, method: :delete %></button>
        			     <% else %>
        			 	    <button class="btn btn-success navbar-btn my-2 my-sm-0"><%= link_to "Entrar", user_session_path %></button>
        			     <% end %>
                    </form>
      			</div>
    		</nav>
    			
			<h1 class="brand-quote">Pretende doar ou vender?</h1>	
			<h1 class="brand-quot" style="color:#80FF00">Anuncie seu livro aqui.</h1>
			<p class="para"><strong>Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.</strong></p>
		</section>
			
	</body>

</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SiteLivros</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/show.html.erb
<!DOCTYPE html>

<html lang="pt-br">

	<head>
		
		<meta charset="utf-8">
    	<meta name="viewport" content="width=device-width, initial-scale=1">
    	<link rel="stylesheet" href="css/bootstrap.min.css">
    	<link rel="stylesheet" href="css/style.css">
    	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    	<link href="https://fonts.googleapis.com/css?family=Abel|Montserrat|Patua+One" rel="stylesheet">
    	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script> 

	</head>

	<body>

		<nav class="navbar navbar-inverse">
      		<div class="container-fluid">
        		<div class="navbar-header">
        			<div class="navbar-brand" style="color: #fff"><div style="font-family: 'Patua One', cursive">Venda/Doação de Livros</div></div>
        		</div>
        		<ul class="nav navbar-nav">
        			<li><a href="/" style="color: #fff">Home</a></li>
        			<li><a href="/books" style="color: #fff">Livros</a></li>
        			<li><a href="#" style="color: #fff">Sobre</a></li>
        			<li><a href="#" style="color: #fff">Contato</a></li>
        		</ul>
                <form class="form-inline my-2 my-lg-0">
        			<% if user_signed_in? %>
        			 	<button class="btn btn-primary navbar-btn"><%= link_to "Perfil", user_path(current_user) %></button>
        				<button class="btn btn-danger navbar-btn"><%= link_to "Sair", destroy_user_session_path, method: :delete %></button>
        			<% else %>
        			 	<button class="btn btn-success navbar-btn my-2 my-sm-0"><%= link_to "Entrar", user_session_path %></button>
        			<% end %>
                </form>
      		</div>
    	</nav>
    	
    	<div class="container">
    		<h1>Perfil</h1>
    		<div class="col-sm-7">
      			<h2>Meus dados</h2>
      			<hr>      
      			<label>Email:</label>
      			<%= @user.email %>
      			<br>
      			<br>
      			<button type="submit" class="btn btn-primary">Editar dados</a>
      		</div>

      		<div class="col-sm-7">
      			<br>
      			<br>
      			<h2>Meus livros anunciados</h2>
      			<hr>      
      			<% @user_books.each do |books| %>
					<strong><%= link_to books.titulo, books %></strong><br>
				<% end %>
      		</div>
      	</div>
			
	</body>

</html>